name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Shards Test (OTP ${{ matrix.otp }})'

    strategy:
      matrix:
        otp: [23.1, 22.3]

    steps:
      - uses: actions/checkout@v2
      - uses: gleam-lang/setup-erlang@v1.1.0
        with:
          otp-version: ${{ matrix.otp }}

      - name: Running Tests
        run: make test

      - name: Running Edoc
        run: make docs

      - name: Running Xref
        run: make xref

      - uses: actions/cache@v1
        with:
          path: priv/plts
          key: ${{ runner.os }}-plt-v1-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.lock')) }}
          restore-keys: |
            ${{ runner.os }}-plt-v1-

      - name: Running Dialyzer
        run: make dialyzer
